name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Trigger only when pushing to main
  pull_request:
    branches:
    - main  # Trigger on pull requests targeting main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

        # Login to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

        # Set up Docker Build
      - name: Build image
        run: docker build -t "${{ secrets.DOCKER_HUB_USERNAME }}/final-python:latest" .

        # Push the Docker image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/final-python:latest"